### ISSUE TITLE
为啥我用安装完后指显示{"code":-1,"data":null}

### ISSUE THREAD

**Issue by EveElseIf** [1574242600/Phpure-Danmaku#1]
为啥我用安装完后指显示{"code":-1,"data":null}，帮忙解答一下，谢谢

**Comment by 1574242600** [comment]
如果没带任何参数，直接访问接口
如：https://demo.nworm.cf/danmu/v3/
是正常的

**Comment by EveElseIf** [comment]
不好意思，我傻了，没看到没有后台。给您星星了

**Comment by EveElseIf** [comment]
昨天花了几个小时弄docker被下载速度搞崩溃了，下载好了又发现不能用，您这真算是神器了

**Comment by EveElseIf** [comment]
对了，我报个问题，就是我用的mariadb，如果用pdo没问题，mysqli会报错

创建数据表错误: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SET time_zone = '+08:00'; SET foreign_key_checks = 0; SET sql_mode = 'NO_AUTO_VA' at line 2

**Comment by 1574242600** [comment]
这是我的锅，现在应该行了
