### ISSUE TITLE
弹幕加载失败

### ISSUE THREAD

**Issue by Rocket2333** [1574242600/Phpure-Danmaku#2]
安装完成后，dplayer弹幕库的参数该如何设置呢？
尝试多次后还是不明白，但是添加bilibili弹幕是可以的
```
danmaku: {
        id: '2333',
        api: 'http://danmu.xxx.xxx/v3/?id=',
    },
```

**Comment by 1574242600** [comment]
http://danmu.xxx.xxx/

不需要 “v3/?id=”

这事不应该问我，你应该去看dplayer的指南
http://dplayer.js.org/zh/guide.html

**Comment by Rocket2333** [comment]
我还是有疑问，如果用您的演示站，这段该如何设置id和api。
使用别人搭建好的接口，直接按照官方指南就可以设置好，如下：
```
    danmaku: {
        id: '1da9241006a3a1a3',
        api: 'https://dplayer.alone88.cn/',
    },
```
如果使用您的弹幕库，该如何设置，这是我一直没搞懂的。。
```
    danmaku: {
        id: '1da9241006a3a1a3',
        api: 'https://demo.nworm.cf/danmu/',
    },

```

**Comment by 1574242600** [comment]
取决于接口所在的路径
假设web根目录为 / 

|接口所在目录 | url |
|----| ------|
|/    | https://demo.nworm.cf/ |
|/danmu | https://demo.nworm.cf/danmu/ |
| /*  | https://demo.nworm.cf/*/  |

不得不说，还是路由好用，23333
